import { UserConfig } from "./user.types";
import {
  blueSkyIcon,
  githubIcon,
  instagramIcon,
  linkedinIcon,
  xIcon,
} from "linkfolio/dist/assets";

const userConfig: UserConfig = {
  avatarSrc: "/assets/avatar.webp",
  avatarAlt: "Avatar",
  fullName: "Alexandre Mogère",
  alias: "@heristop",
  metaTitle: "Alexandre Mogère",
  metaDescription: "Alexandre Mogère's Links",
  enableTypingAlias: true,
  darkTheme: {
    "color-primary": "#c8a8d4",
    "color-secondary": "#d4a0be",
    "color-background-start": "#1a1424",
    "color-background-end": "#1e1829",
    "lf-card-bg": "#261e30",
    "lf-card-shadow":
      "0 2px 4px rgba(0,0,0,0.2), 0 8px 32px -8px rgba(0,0,0,0.4)",
    "lf-card-border": "1px solid rgba(200,168,212,0.08)",
    "lf-name-color": "#e0d0ea",
    "lf-alias-color": "#d4a0be",
    "lf-network-hover-bg": "rgba(200,168,212,0.06)",
    "lf-accent-line-color": "#d4a0be",
    "lf-accent-line-opacity": "0.5",
    "lf-button-opacity": "0.8",
  },
  socialNetworks: [
    {
      url: "https://github.com/heristop",
      iconSrc: githubIcon,
      title: "GitHub",
      description: "Open-source Contributions",
      group: "socialnetwork",
    },
    {
      url: "https://instagram.com/heristop",
      iconSrc: instagramIcon,
      title: "Instagram",
      description: "Art & travel Snapshots",
      group: "socialnetwork",
    },
    {
      url: "https://www.linkedin.com/in/heristop",
      iconSrc: linkedinIcon,
      title: "LinkedIn",
      description: "Professional Overview",
      group: "socialnetwork",
    },
    {
      url: "https://bsky.app/profile/heristop.bsky.social",
      iconSrc: blueSkyIcon,
      title: "BlueSky",
      description: "Tech watch & insights",
      group: "socialnetwork",
    },
    {
      url: "https://x.com/heristop",
      iconSrc: xIcon,
      title: "X",
      description: "Tech Monitoring",
      group: "socialnetwork",
    },
    {
      url: "https://heristop.github.io",
      iconSrc: "/assets/zazen.webp",
      title: "Zazen Code",
      description: "Tech Blog",
      group: "website",
    },
    {
      url: "https://gutenku.xyz",
      iconSrc: "/assets/gutenku.webp",
      title: "GutenKu",
      description: "AI Haiku Generator",
      group: "project",
    },
    {
      url: "https://pix-me.studio",
      iconSrc: "/assets/pix-me.webp",
      title: "Pix Me!",
      description: "AI Avatar Generator",
      group: "project",
    },
    {
      url: "https://chatodo.app",
      iconSrc: "/assets/chatodo.webp",
      title: "ChaTodo",
      description: "ADHD-Friendly To-Do List & Task Manager",
      group: "project",
    },
    {
      url: "https://clover-map.nuxt.dev",
      iconSrc: "/assets/clover-map.webp",
      title: "Clover Map",
      description: "Project Management Tool",
      group: "project",
    },
    {
      url: "https://linkfolio-demo.vercel.app",
      iconSrc: "/assets/linkfolio.webp",
      title: "Linkfolio",
      description: "Portfolio Demo",
      group: "project",
      hidden: true,
    },
  ],
};

export default userConfig;
